// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

library MiscMonad {
  // https://monadscan.com/address/0x2f09b9D890535c2b5c81b1b95F7f92eeed5B9d5D
  address internal constant TRANSPARENT_PROXY_FACTORY = 0x2f09b9D890535c2b5c81b1b95F7f92eeed5B9d5D;

  // https://monadscan.com/address/0xc887455536CBD4e615B745e70CaCde15B3117e74
  address internal constant PROTOCOL_GUARDIAN = 0xc887455536CBD4e615B745e70CaCde15B3117e74;

  // https://monadscan.com/address/0xa1Cf1e3D3fC743c0fd0e38f631A843372b7169DB
  address internal constant AGENT_HUB = 0xa1Cf1e3D3fC743c0fd0e38f631A843372b7169DB;

  // https://monadscan.com/address/0x863D5B3f24E6b84564432dd20606a82bB1C61dC5
  address internal constant RANGE_VALIDATION_MODULE = 0x863D5B3f24E6b84564432dd20606a82bB1C61dC5;

  // https://monadscan.com/address/0x1a0267E9E5929a5914Ae9DbBf23Bc07B14365471
  address internal constant LLAMARISK_RISK_ORACLE_ADMIN_SAFE =
    0x1a0267E9E5929a5914Ae9DbBf23Bc07B14365471;

  // https://monadscan.com/address/0x4b00A38ee9396E952d07F81B26Ed1514e480dCFC
  address internal constant LLAMARISK_RISK_ORACLE = 0x4b00A38ee9396E952d07F81B26Ed1514e480dCFC;

  // https://monadscan.com/address/0xA046b090C93A7a98b18e466ff770ED01116fa695
  address internal constant LLAMARISK_PT_PARAMETER_REGISTRY =
    0xA046b090C93A7a98b18e466ff770ED01116fa695;

  // https://monadscan.com/address/0x8fDdd4Ab11Ecd6A95F6d67f13166031604624B71
  address internal constant LLAMARISK_RISK_ORACLE_ROUTER =
    0x8fDdd4Ab11Ecd6A95F6d67f13166031604624B71;

  // https://monadscan.com/address/0x9047f3084Dd26d0d8a6b0Ef9Bb8643b01dA726D3
  address internal constant LLAMARISK_PT_DISCOUNT_RATE_AGENT =
    0x9047f3084Dd26d0d8a6b0Ef9Bb8643b01dA726D3;

  // https://monadscan.com/address/0xa89C6f877380af190AFD839c0F9cBF57474162f1
  address internal constant LLAMARISK_PT_EMODE_AGENT = 0xa89C6f877380af190AFD839c0F9cBF57474162f1;

  // https://monadscan.com/address/0xAA2461f0f0A3dE5fEAF3273eAe16DEF861cf594e
  address internal constant AHAB_SAFE = 0xAA2461f0f0A3dE5fEAF3273eAe16DEF861cf594e;

  // https://monadscan.com/address/0xA1c93D2687f7014Aaf588c764E3Ce80aF016229b
  address internal constant ALC_SAFE = 0xA1c93D2687f7014Aaf588c764E3Ce80aF016229b;

  // https://monadscan.com/address/0x9DE1d45e2786b03498289959203F25b29B4D1193
  address internal constant TOKENLOGIC_EXECUTION_SAFE = 0x9DE1d45e2786b03498289959203F25b29B4D1193;

  // https://monadscan.com/address/0x22740deBa78d5a0c24C58C740e3715ec29de1bFa
  address internal constant AFC_SAFE = 0x22740deBa78d5a0c24C58C740e3715ec29de1bFa;

  // https://monadscan.com/address/0x66Ac7223048037826e12cef9a848199e31AEFabE
  address internal constant BUDGET_INCENTIVE_SAFE = 0x66Ac7223048037826e12cef9a848199e31AEFabE;

  // https://monadscan.com/address/0x89587ebe7cFF64c6527fE2Deccc3521D75763E8D
  address internal constant MERKL_DISTRIBUTION_SAFE = 0x89587ebe7cFF64c6527fE2Deccc3521D75763E8D;
}
